image: node:latest

stages:
  - test
  - build
  - publish

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn
    - yarn test

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - lib/

publish:
  stage: publish
  dependencies:
    - build
  script:
    - cat ~/.npmrc
    - yarn info
    - ls
