image: node:latest

cache:
  paths:
    - node_modules/

test:
  script:
    - yarn
    - yarn test

build:
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - lib/

publish:
  dependencies:
    - build
  script:
    - cat ~/.npmrc
    - yarn info
    - ls