image: node:latest

stages:
  - test
  - build
  - publish

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn
    - yarn test

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - lib/

publish:
  stage: publish
  when: manual
  only:
    - tags
  dependencies:
    - build
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - yarn publish --access public --new-version $(node -p "require('./package.json').version")
